### PR TITLE
Admin panel and front end changes

### PR DESCRIPTION
**Pull request by rafaeloaguir**
Internal Issue#2

This version of Gravity has been optimized to provide consistent JavaScript styling throughout the existing application files as well as generated files. Additionally, an admin panel has been added that will allow application owner/developer view data recorded in the blockchain. This admin panel provides read-only capabilities for now.
Several front end updates have been made.
Admin panel code requires a new env variable: APP_ACCOUNT_ID. It can be set to anything.

### CODE REVIEW

**Comment by sigwo** [comment]
Reviewing and updating documentation sources.

**Comment by rafaeloaguirre** [comment]
Force pushed a rebased version of front-end and  back-end branches. Manually solved merger issues and tested  basic functionalities.

**Comment by sigwo** [comment]
So far I don't see any issues with #14. Will merge if no issues or concerns raised in dev meeting on Sunday.

**Comment by sigwo** [comment]
@rafaeloaguir Is this a go for merging_branch to master?

**Comment by rafaeloaguir** [comment]
@sigwo  Sorry Steven. Forgot to respond. We first need to merge Kyle's PR into this one. You approved it so I 'll just give it a look, approve it and then merge it to this branch.

**Comment by rafaeloaguir** [comment]
@sigwo @kyle-hensman  Merged the fix-typos branch with the merging_branch. I need to implement thec changes by let's try this but if you two give this branch a test run and see nothing wrong with it, I think we can merge to master.

**Pull request merged**
